name: xesmf
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - cf_xarray>=0.5.1
  - dask
  - esmpy
  - numba >=0.55.2
  - numpy >=1.16
  - shapely
  - sparse>=0.8.0
  - xarray>=0.17.0
  # Testing and extras
  - cftime
  - codecov
  - netcdf4
  - pip
  - pre-commit
  - pytest
  - pytest-cov
